const assert=require('node:assert/strict');
const {select,dateNumber,dateRange,estimateGB,fitStatus,encodeState,decodeState}=require('../web/app.js');
const data=require('../data/catalog.json');
let rows=select(data.products,{},'memory_gb',1);
assert.equal(rows[0].memory_gb,Math.min(...data.products.map(p=>p.memory_gb)));
assert.ok(rows.findIndex(x=>x.memory_gb===128)<rows.findIndex(x=>x.memory_gb===1440));
rows=select(data.products,{vendor:'AMD',q:'R9700'},'model',1);
assert.equal(rows.length,1);assert.equal(rows[0].vendor,'AMD');
assert.equal(select(data.products,{q:'unmatched-query'},'model',1).length,0);
rows=select(data.products,{},'power_w',-1);assert.equal(rows.at(-1).power_w,null);
assert.ok(dateNumber('2025-Q1')<dateNumber('2025-10-15'));
assert.ok(dateNumber('2026-H2')<dateNumber('2026-end'));
assert.equal(dateNumber(null),null);
assert.equal(data.products.find(x=>x.id==='dgx-spark-gb10').release,'2025-10-15');
const [q3s,q3e]=dateRange('2025-Q3');assert.equal(new Date(q3s).toISOString().slice(0,10),'2025-07-01');assert.equal(new Date(q3e).toISOString().slice(0,10),'2025-09-30');
assert.equal(new Date(dateRange('2025-Summer')[1]).toISOString().slice(0,10),'2025-08-31');assert.equal(dateRange('soon'),null);
assert.equal(estimateGB(70,4,20),42);assert.equal(estimateGB('',4,20),null);assert.equal(estimateGB(8,16,0),16);
assert.equal(fitStatus({memory_gb:48,memory_scope:'Per GPU'},42),'fits');assert.equal(fitStatus({memory_gb:768,memory_scope:'System total'},42),'multi');assert.equal(fitStatus({memory_gb:32,memory_scope:'Per GPU'},42),'no');assert.equal(fitStatus({memory_gb:32},null),null);
rows=select(data.products,{need:42,fitOnly:true},'memory_gb',1);assert.ok(rows.length>0&&rows.every(p=>p.memory_gb>=42));
const st={...decodeState(''),q:'mi3',vendor:'AMD',sort:'memory_gb',dir:-1,view:'table',cmp:['h200','b200-blackwell'],lang:'ar',params:'70',fit:true};
const back=decodeState(encodeState(st));for(const k of Object.keys(st))assert.deepEqual(back[k],st[k],k);
assert.equal(encodeState(decodeState('')),'');assert.equal(decodeState('?view=evil&lang=xx').view,'cards');assert.equal(decodeState('?cmp=a,b,c,d,e,a').cmp.length,4);
console.log('PASS: sort, date windows, nulls, filters, Spark date, estimator, fit, URL state');
